title: Life of a new Developer
author: HorrocksVAC
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Starting with Git and then GitHub training, going very slow.
# social links
twitter_username: Twitter # DO NOT include the @ character, or else the build will fail!
github_username:  Horrocksvac-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
